### ISSUE TITLE
If it is possible to boost the speed of running? 

### ISSUE THREAD

**Issue by wbhu** [silenceshell/docker_mirror#1]
This tool is very exciting, and I love it very much. But the speed of pulling the Cent OS image is too slow, I think if we could use other faster methods to test the mirror servers's speed, we can make this fancy tool easier to use.

**Comment by silenceshell** [comment]
yeah because this script will try to pull centos image from many mirrors, so it indeed costs a lot of time. May be I should set a timer for every pulling?

**Comment by silenceshell** [comment]
use `registry:2` instead.
