### ISSUE TITLE
Docker 官方中国源貌似挂了

### ISSUE THREAD

**Issue by XhstormR** [silenceshell/docker_mirror#5]
一个月前我访问 `https://registry.docker-cn.com`，就是下面的情况连接超时：
```
C:\Users\XhstormR>curl -ik https://registry.docker-cn.com
curl: (7) Failed to connect to registry.docker-cn.com port 443: Timed out
```

今天我访问 `https://www.docker-cn.com/get-docker`，发现跳到 www.docker.com 了，貌似 Docker 不打算提供中国服务了。

**Comment by XhstormR** [comment]
https://github.com/docker/docker.github.io/issues/8793

**Comment by silenceshell** [comment]
确实挂了。

可以帮忙提交一个PR删掉docker-cn吗？

**Comment by silenceshell** [comment]
closed #6
